---
title: "Quantile Regressions"
author: "Gorlevich Daniil"
date: "2023-12-09"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
##
```{r}
library(readxl)
library(zoo)
library(quantreg)
library(ggplot2)
library(stringr)

options(scipen=999)
```

## Load and preprocess data

```{r}
data <- read_excel("EXDATA.xlsx")
date <- data$Date
values <- subset(data, select = -c(Date))
zoo_values <- zoo(values, order.by = date)
ts_no_dates <- ts(values)
autoplot(zoo_values, nc = 1) + 
  facet_free()
```

## Quantile Augmented Dickey-Fuller Test

Select ARDF lag and trend presence:

```{r}
ARDF_lag_selection <- function(variable, tau, dq_max = 7) {
  # Just lag selection through median AIC
  print(str_glue("Selecting lags"))
  AIC_min <- 0
  best_dq <- 1 
  for (dq in 1:dq_max) {
    model <- dynrq(variable ~ 
                     trend(variable) + 
                     L(variable, 1:dq),
                   tau = tau, start = dq_max)
    AIC_ <- median(AIC(model))
    if (AIC_ < AIC_min) {
      AIC_min <- AIC_
      best_dq <- dq
    } 
  }
  print(str_glue("Optimal lags: {best_dq}"))
  # Model for ADF-test
  print(str_glue("Fitting ADF"))
  ADF_model <- dynrq(d(variable) ~ 
                       trend(variable) + 
                       L(variable, 1) + 
                       L(diff(variable), 1:max(1, best_dq-1)),
                     tau = tau)
  taus <- c()
  coeffs <- c()
  t_stats <- c()
  p_values <- c()
  summaries <- summary(ADF_model, se = "boot")
  print(str_glue("Building df"))
  for (tau_index in seq_along(summaries)) {
    taus <- c(taus, tau[tau_index])
    per_tau_summary <- summaries[[tau_index]]
    per_tau_coeff <- coefficients(per_tau_summary)
    coeffs <- c(coeffs, round(per_tau_coeff[3, 1], digits=4))
    t_stats <- c(t_stats, round(per_tau_coeff[3, 3], digits=2))
    p_values <- c(p_values, round(per_tau_coeff[3, 4], digits=2))
  }
  return(data.frame(coeffs = coeffs,
                    t_stat = t_stats,
                    p_value = p_values))
}
```

Check for trend significance:

```{r}
tau <- seq(0.1, 0.9, 0.1)
results <- data.frame(tau = tau)
for (var in c("ER", "EPU", 
              "OP", "MC", 
              "TRD")) {
  print(str_glue("VAR: {var}"))
  series <- ts_no_dates[, var]
  var_result <- ARDF_lag_selection(series, 
                                   tau = tau)
  colnames(var_result) <- paste(
    str_glue("{var}:"), 
    colnames(var_result)
    )
  results <- cbind(results, var_result)
  print(str_glue("------"))
}
```

```{r}
```
## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
